This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./dissertation.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (323 entries accepted, 0 rejected).
Sorting entries......done (3313 comparisons).
Generating output file dissertation.acr....done (137 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
