This is makeindex, version 2.16 [MiKTeX 22.8].
Scanning style file ./dissertation.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (374 entries accepted, 0 rejected).
Sorting entries......done (3646 comparisons).
Generating output file dissertation.acr....done (177 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
